from __future__ import annotations

"""
build_sitemap.py — Feedsmith sitemap generator (multilingual).

Emits sitemap.xml with one <url> entry per page per language, each carrying
the full xhtml:link hreflang cluster (en/de/fr/it + x-default=en).
Run after adding pages or targets:  python3 tools/build_sitemap.py
"""

import json
from pathlib import Path

BASE = "https://feedsmith.net"
ROOT = Path(__file__).resolve().parent.parent
LANGS = ("en", "de", "fr", "it")

OFFERS = ["hidden-api-audit", "scraper", "managed-data-feed", "discord-bot"]
GUIDES = [
    "what-is-a-hidden-api",
    "no-code-scraper-keeps-breaking",
    "cloudflare-protected-public-sites",
]


def url_for(lang: str, rel: str) -> str:
    prefix = "" if lang == "en" else f"{lang}/"
    return f"{BASE}/{prefix}{rel}"


def cluster(rel: str) -> str:
    lines = [
        f'    <xhtml:link rel="alternate" hreflang="{l}" href="{url_for(l, rel)}"/>'
        for l in LANGS
    ]
    lines.append(
        f'    <xhtml:link rel="alternate" hreflang="x-default" href="{url_for("en", rel)}"/>'
    )
    return "\n".join(lines)


def entry(lang: str, rel: str, changefreq: str, priority: str) -> str:
    return (
        "  <url>\n"
        f"    <loc>{url_for(lang, rel)}</loc>\n"
        f"{cluster(rel)}\n"
        f"    <changefreq>{changefreq}</changefreq>\n"
        f"    <priority>{priority}</priority>\n"
        "  </url>"
    )


def main() -> None:
    targets = json.loads((ROOT / "tools" / "targets.json").read_text(encoding="utf-8"))
    scrape_slugs = [t["slug"] for t in targets]

    blocks: list[str] = []
    blocks.append("  <!-- Home pages -->")
    for lang in LANGS:
        blocks.append(entry(lang, "", "weekly", "1.0" if lang == "en" else "0.9"))

    blocks.append("\n  <!-- Offer pages -->")
    for slug in OFFERS:
        for lang in LANGS:
            blocks.append(entry(lang, f"offers/{slug}.html", "monthly", "0.8" if lang == "en" else "0.7"))

    blocks.append("\n  <!-- Guide pages -->")
    for slug in GUIDES:
        for lang in LANGS:
            blocks.append(entry(lang, f"guides/{slug}.html", "monthly", "0.7" if lang == "en" else "0.6"))

    blocks.append("\n  <!-- Scrape (pSEO) pages -->")
    for slug in scrape_slugs:
        for lang in LANGS:
            blocks.append(entry(lang, f"scrape/{slug}.html", "monthly", "0.6" if lang == "en" else "0.5"))

    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!--\n"
        "  Feedsmith sitemap — GENERATED by tools/build_sitemap.py, do not edit by hand.\n"
        "  Every page exists in EN/DE/FR/IT; each entry carries the full hreflang cluster.\n"
        "-->\n"
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n'
        '        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n\n'
        + "\n".join(blocks)
        + "\n\n</urlset>\n"
    )
    (ROOT / "sitemap.xml").write_text(xml, encoding="utf-8")
    count = xml.count("<loc>")
    print(f"sitemap.xml written — {count} URLs")


if __name__ == "__main__":
    main()
